### ISSUE TITLE
crash on High Sierra

### ISSUE THREAD

**Issue by grylem** [kaunteya/MacCacheCleaner#2]
Hi
app quit after some time and crash

> Crashed Thread:        4  Dispatch queue: NSOperationQueue 0x6000002223e0 (QOS: UNSPECIFIED)
......
Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
terminating with uncaught exception of type NSException
abort() called

Regards.

**Comment by kaunteya** [comment]
Check out the new version for the bug fix
